# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_auto_20170418_1438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Volunteer',
            new_name='Member',
        ),
    ]
