# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_auto_20170418_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(blank=True, max_length=50)),
                ('street_address', models.CharField(max_length=50)),
                ('locality', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('latitude', models.FloatField(blank=True, max_length=30)),
                ('longitufe', models.FloatField(blank=True, max_length=30)),
            ],
        ),
    ]
